### ISSUE TITLE
Dask tutorial doesn't work

### ISSUE THREAD

**Issue by myousefi2016** [NVIDIA/ipyparaview#14]
I'm trying to use `ipyparaview` with this configuration:

OS: Linux login001 4.14.35-1902.6.6.el7uek.x86_64 #2 SMP Tue Oct 8 07:32:21 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

Conda version: conda 4.4.10

ParaView version: 5.8.0-RC2

I have no problem to run the `Hello_Jupyter-ParaView` example. But when I run `Dask-MPI_Volume_Render` example, At the very end I got this error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-5b6780ffd429> in <module>
      1 from paraview.simple import *
      2 from ipyparaview.widgets import PVDisplay
----> 3 w = PVDisplay(renderers)
      4 display(w)

~/ipyparaview/ipyparaview/widgets.py in __init__(self, ren, runAsync, **kwargs)
     93             #        lambda self : list(self.renv.CameraPosition),
     94             #        []).result()
---> 95             self.resolution = tuple(self.renv.ViewSize)
     96 
     97             cf = self.renv.CameraFocalPoint

~/.conda/envs/ipy_dev/lib/python3.7/site-packages/distributed/actor.py in __getattr__(self, key)
    120 
    121     def __getattr__(self, key):
--> 122         attr = getattr(self._cls, key)
    123 
    124         if self._future and self._future.status not in ("finished", "pending"):

AttributeError: type object 'PVRenderActor' has no attribute 'ViewSize'
```
Any idea what's wrong here?

**Comment by NickLeaf** [comment]
Yeah, I think the likely culprit is that some refactoring didn't make it into the RenderActor--the internal name of the RenderView should be "renv" instead of "renV". I'll see if that change fixes it and update in a bit.

**Comment by NickLeaf** [comment]
It ended up being a bit more extensive than just the name change, but #15 should fix it. At least, I was able to get it to work with my setup.

**Comment by NickLeaf** [comment]
Closing unless there's something new here.
