### ISSUE TITLE
Win32OpenGL Window

### ISSUE THREAD

**Issue by josephwinston** [NVIDIA/ipyparaview#4]
First, great work.  This makes my life easier when I am incorporating ParaView into Jupyter.

Question: On Windows 10, when I run `http://localhost:8888/notebooks/Untitled.ipynb` a window with the title "Visualization Toolkit - Win32OpenGL #X", where X is some number is opened.  Then the notebook shows the visualization.  The window outside of the notebook then adds to the title "(Not Responding)".    Once the notebook is shutdown, the window is removed.   Is there anyway to hide this window since it might confuse users?

**Comment by NickLeaf** [comment]
I'm glad the project is useful. =)

The external window is a side-effect of the ParaView build that you're using. The default ParaView build from Kitware and the one on conda-forge are both built without support for headless rendering. On Linux, I usually use a custom ParaView build with EGL support enabled. I'm not sure what the equivalent headless rendering solution is for Windows.

**Comment by josephwinston** [comment]
Excellent.
